# Generated by Django 4.0.6 on 2022-11-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=30)),
                ('sales', models.CharField(max_length=30)),
                ('marketing', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=30)),
            ],
        ),
    ]
