# Generated by Django 4.0.6 on 2022-12-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
    ]
