# Generated by Django 4.0.6 on 2022-11-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.ForeignKey(default='Management', on_delete=django.db.models.deletion.CASCADE, to='Kanban.category'),
        ),
    ]
