# Generated by Django 4.0.6 on 2023-02-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0002_myuser_groups_myuser_user_permissions'),
        ('Kanban', '0002_user'),
    ]

    operations = [
    ]
