# Generated by Django 4.0.6 on 2023-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0005_remove_task_user_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=15),
        ),
    ]
