# Generated by Django 4.0.6 on 2022-11-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0005_alter_tasks_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='management',
        ),
        migrations.RemoveField(
            model_name='category',
            name='marketing',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sales',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('management', 'MANAGEMENT'), ('sales', 'SALES'), ('marketing', 'MARKETING'), ('product', 'PRODUCT')], default='management', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kanban.category'),
        ),
    ]
