# Generated by Django 4.0.6 on 2022-11-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0006_remove_category_management_remove_category_marketing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
