# Generated by Django 4.0.6 on 2022-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0007_remove_category_id_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('management', 'MANAGEMENT'), ('sales', 'SALES'), ('marketing', 'MARKETING'), ('product', 'PRODUCT')], max_length=10),
        ),
    ]
