# Generated by Django 4.0.6 on 2023-05-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0009_subtask_task_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='Kanban.task'),
        ),
    ]
