# Generated by Django 4.0.6 on 2022-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0009_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('management', 'MANAGEMENT'), ('sales', 'SALES'), ('marketing', 'MARKETING'), ('product', 'PRODUCT')], default=0, max_length=10),
        ),
    ]
