# Generated by Django 4.0.6 on 2022-11-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0010_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('MT', 'MANAGEMENT'), ('SL', 'SALES'), ('MK', 'MARKETING'), ('PR', 'PRODUCT')], default='MT', max_length=2),
        ),
    ]
