# Generated by Django 4.0.6 on 2023-05-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0012_contacts_myuser_mycontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='myContacts',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='Kanban.contacts'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='Kanban.subtask'),
        ),
    ]
