# Generated by Django 4.0.6 on 2023-06-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0013_alter_myuser_mycontacts_alter_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='myContacts',
        ),
        migrations.AddField(
            model_name='myuser',
            name='myContacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='Kanban.contacts'),
        ),
    ]
