# Generated by Django 4.0.6 on 2023-06-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0014_remove_myuser_mycontacts_myuser_mycontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='myContacts',
        ),
        migrations.AddField(
            model_name='myuser',
            name='myContacts',
            field=models.ManyToManyField(blank=True, related_name='users', to='Kanban.contacts'),
        ),
    ]
