# Generated by Django 4.0.6 on 2023-07-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0015_remove_myuser_mycontacts_myuser_mycontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Management', 'MANAGEMENT'), ('Sales', 'SALES'), ('Marketing', 'MARKETING'), ('Product', 'PRODUCT')], default='MT', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('High', 'HIGH'), ('Mid', 'MEDIUM'), ('Low', 'LOW')], default='H', max_length=10),
        ),
    ]
